### ISSUE TITLE
Your apple ID. was used.....notifications

### ISSUE THREAD

**Issue by casper181** [magtimmermans/com.cyclone-software.familyiphone#2]
I'm getting emails every 5 mins saying my ID has been used to log in on a browser

**Comment by magtimmermans** [comment]
Which version? It should reuse the session and only do this once. This means that somehow the connection between Homey and Apple kill the session. Please try the latest version 1.0.5 (Not in the store yet).

**Comment by casper181** [comment]
1.0.1

I'm a newbie. No idea how to update an app not from the store. Sorry


On 30 January 2019 20:07:32 magtimmermans <notifications@github.com> wrote:

Which version? It should reuse the session and only do this once. This means that somehow the connection between Homey and Apple kill the session. Please try the latest version 1.0.5 (Not in the store yet).

-

**Comment by magtimmermans** [comment]
Aha, ok. Then wait until it is approved. So remove it for now.
