### ISSUE TITLE
Your apple ID. was used.....notifications

### ISSUE THREAD

**Issue by casper181** [magtimmermans/com.cyclone-software.familyiphone#4]
Installed 1.0.5 but issue is still occurring

**Comment by magtimmermans** [comment]
You will get this a few times or every x minutes? If this is the case I cannot fix this as then the connection will be dropped by your router/modem/firewall or homey. Normally you will get this a few times when it needs to reconnect. I am running the app for 2 days and had only one email....

**Comment by magtimmermans** [comment]
Please also check in the log tab if it says reusing connection or connection lost... Something like this.

**Comment by casper181** [comment]
It's happening every 5 minutes. 

Log tab?

**Comment by casper181** [comment]
No log tab. Just the ability to create a diagnostics report

**Comment by casper181** [comment]
Where can I send you these (rather not post on here)

**Comment by magtimmermans** [comment]
Could you send it with a direct message on the https://community.athom.com?
